//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Auditoria
    {
        public System.DateTime TiempoEvento { get; set; }
        public string NombreInicioSesion { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreBaseDatos { get; set; }
        public string NombreEsquema { get; set; }
        public string NombreObjeto { get; set; }
        public string TipoObjeto { get; set; }
        public string ComandoDDL { get; set; }
    }
}
