//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Categoria
    {
        public TB_Categoria()
        {
            this.TB_Producto = new HashSet<TB_Producto>();
        }
    
        public int ID_Categoria { get; set; }
        public string TipoCategoria { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TB_Producto> TB_Producto { get; set; }
    }
}
