//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cliente
    {
        public TB_Cliente()
        {
            this.TB_Pedido = new HashSet<TB_Pedido>();
        }
    
        public int ID_Cliente { get; set; }
        public int ID_Vendedor { get; set; }
        public int ID_Ciudad { get; set; }
        public int ID_Documento { get; set; }
        public string NombreCompleto { get; set; }
        public string NumeroDocumento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
    
        public virtual TB_Ciudad TB_Ciudad { get; set; }
        public virtual TB_Documento TB_Documento { get; set; }
        public virtual TB_Vendedor TB_Vendedor { get; set; }
        public virtual ICollection<TB_Pedido> TB_Pedido { get; set; }
    }
}
