
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TB_Documento
{

    public TB_Documento()
    {

        this.TB_Cliente = new HashSet<TB_Cliente>();

    }


    public int ID_Documento { get; set; }

    public string TipoDocumento { get; set; }



    public virtual ICollection<TB_Cliente> TB_Cliente { get; set; }

}

}
