
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TB_Producto
{

    public TB_Producto()
    {

        this.TB_DetallePedido = new HashSet<TB_DetallePedido>();

    }


    public int ID_Producto { get; set; }

    public int ID_Categoria { get; set; }

    public int ID_Promocion { get; set; }

    public string NombreProducto { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string Fabricante { get; set; }

    public int Stock { get; set; }

    public decimal Impuesto { get; set; }

    public decimal ValorUnitario { get; set; }

    public bool Estado { get; set; }



    public virtual TB_Categoria TB_Categoria { get; set; }

    public virtual ICollection<TB_DetallePedido> TB_DetallePedido { get; set; }

    public virtual TB_Promocion TB_Promocion { get; set; }

}

}
