//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vendedor
    {
        public TB_Vendedor()
        {
            this.TB_Cliente = new HashSet<TB_Cliente>();
        }
    
        public int ID_Vendedor { get; set; }
        public int ID_Ciudad { get; set; }
        public string NombreCompleto { get; set; }
        public string NumeroDocumento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
    
        public virtual TB_Ciudad TB_Ciudad { get; set; }
        public virtual ICollection<TB_Cliente> TB_Cliente { get; set; }
    }
}
