

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCFDAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class DB_Acme_DevEntities : DbContext
{
    public DB_Acme_DevEntities()
        : base("name=DB_Acme_DevEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<TB_Auditoria> TB_Auditoria { get; set; }

    public DbSet<TB_Categoria> TB_Categoria { get; set; }

    public DbSet<TB_Ciudad> TB_Ciudad { get; set; }

    public DbSet<TB_Cliente> TB_Cliente { get; set; }

    public DbSet<TB_DetallePedido> TB_DetallePedido { get; set; }

    public DbSet<TB_Documento> TB_Documento { get; set; }

    public DbSet<TB_Pedido> TB_Pedido { get; set; }

    public DbSet<TB_Perfil> TB_Perfil { get; set; }

    public DbSet<TB_Producto> TB_Producto { get; set; }

    public DbSet<TB_Promocion> TB_Promocion { get; set; }

    public DbSet<TB_Usuario> TB_Usuario { get; set; }


    public virtual int ActualizarStockProducto(Nullable<int> iD_Producto, Nullable<int> cantidad)
    {

        var iD_ProductoParameter = iD_Producto.HasValue ?
            new ObjectParameter("ID_Producto", iD_Producto) :
            new ObjectParameter("ID_Producto", typeof(int));


        var cantidadParameter = cantidad.HasValue ?
            new ObjectParameter("Cantidad", cantidad) :
            new ObjectParameter("Cantidad", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarStockProducto", iD_ProductoParameter, cantidadParameter);
    }


    public virtual int AutenticarUsuario(string nombreUsuario, string contrasenia, ObjectParameter resultado)
    {

        var nombreUsuarioParameter = nombreUsuario != null ?
            new ObjectParameter("NombreUsuario", nombreUsuario) :
            new ObjectParameter("NombreUsuario", typeof(string));


        var contraseniaParameter = contrasenia != null ?
            new ObjectParameter("Contrasenia", contrasenia) :
            new ObjectParameter("Contrasenia", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutenticarUsuario", nombreUsuarioParameter, contraseniaParameter, resultado);
    }


    public virtual int ConsultarIdentificadorPedido(ObjectParameter iD_Pedido)
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConsultarIdentificadorPedido", iD_Pedido);
    }


    public virtual int InsertarDetallePedido(Nullable<int> iD_Pedido, Nullable<int> iD_Producto, Nullable<int> cantidad)
    {

        var iD_PedidoParameter = iD_Pedido.HasValue ?
            new ObjectParameter("ID_Pedido", iD_Pedido) :
            new ObjectParameter("ID_Pedido", typeof(int));


        var iD_ProductoParameter = iD_Producto.HasValue ?
            new ObjectParameter("ID_Producto", iD_Producto) :
            new ObjectParameter("ID_Producto", typeof(int));


        var cantidadParameter = cantidad.HasValue ?
            new ObjectParameter("Cantidad", cantidad) :
            new ObjectParameter("Cantidad", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarDetallePedido", iD_PedidoParameter, iD_ProductoParameter, cantidadParameter);
    }


    public virtual int InsertarPedido(Nullable<int> iD_Cliente, Nullable<decimal> totalBruto, Nullable<decimal> impuesto, Nullable<decimal> valorNeto)
    {

        var iD_ClienteParameter = iD_Cliente.HasValue ?
            new ObjectParameter("ID_Cliente", iD_Cliente) :
            new ObjectParameter("ID_Cliente", typeof(int));


        var totalBrutoParameter = totalBruto.HasValue ?
            new ObjectParameter("TotalBruto", totalBruto) :
            new ObjectParameter("TotalBruto", typeof(decimal));


        var impuestoParameter = impuesto.HasValue ?
            new ObjectParameter("Impuesto", impuesto) :
            new ObjectParameter("Impuesto", typeof(decimal));


        var valorNetoParameter = valorNeto.HasValue ?
            new ObjectParameter("ValorNeto", valorNeto) :
            new ObjectParameter("ValorNeto", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarPedido", iD_ClienteParameter, totalBrutoParameter, impuestoParameter, valorNetoParameter);
    }


    public virtual int InsertarUsuario(string nombreCompleto, string numeroDocumento, string nombreUsuario, string contrasenia)
    {

        var nombreCompletoParameter = nombreCompleto != null ?
            new ObjectParameter("NombreCompleto", nombreCompleto) :
            new ObjectParameter("NombreCompleto", typeof(string));


        var numeroDocumentoParameter = numeroDocumento != null ?
            new ObjectParameter("NumeroDocumento", numeroDocumento) :
            new ObjectParameter("NumeroDocumento", typeof(string));


        var nombreUsuarioParameter = nombreUsuario != null ?
            new ObjectParameter("NombreUsuario", nombreUsuario) :
            new ObjectParameter("NombreUsuario", typeof(string));


        var contraseniaParameter = contrasenia != null ?
            new ObjectParameter("Contrasenia", contrasenia) :
            new ObjectParameter("Contrasenia", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarUsuario", nombreCompletoParameter, numeroDocumentoParameter, nombreUsuarioParameter, contraseniaParameter);
    }

}

}

