
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCFDAL
{

using System;
    using System.Collections.Generic;
    
public partial class TB_Perfil
{

    public int ID_Perfil { get; set; }

    public int ID_Usuario { get; set; }

    public string NombrePerfil { get; set; }

    public string Descripcion { get; set; }



    public virtual TB_Usuario TB_Usuario { get; set; }

}

}
